---
- include_vars: vars/vault.yml

- name: install dns utilities
  apt: name=dnsutils state=latest

- name: install jq
  apt: name=jq state=latest
  
- name: schedule periodic updates of dns entry
  template: src=update-dns.j2 dest=/etc/cron.daily/update-dns
