---

- name: nginx - configure dl
  copy: src=dl.conf dest=/etc/nginx/sites-available/dl.conf

- name: nginx - activate dl
  file:
    src=/etc/nginx/sites-available/dl.conf
    dest=/etc/nginx/sites-enabled/dl.conf
    state=link

- name: add mini-dinstall user
  command: adduser --system --disabled-password --disabled-login --home /var/empty --no-create-home --quiet --force-badname --group mini-dinstall

- name: install mini-dinstall
  apt: name=mini-dinstall state=latest

- name: copy mini-dinstall config
  copy: src=mini-dinstall.conf dest=/etc/mini-dinstall.conf

- name: create mini-dinstall archive directory
  file: path=/srv/dl/debian state=directory owner=mini-dinstall group=mini-dinstall mode=0755

- name: copy mini-dinstall service config
  copy: src=mini-dinstall.service dest=/etc/systemd/system/mini-dinstall.service

- name: enable and start mini-dinstall service
  service: name=mini-dinstall enabled=yes state=started
